name: drugpromotion
description: "Delivery project"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  yandex_mapkit: ^4.1.0
  geolocator: ^13.0.2
  flutter_bloc: ^9.0.0
  intl: ^0.19.0
  dio: ^5.7.0
  get_it: ^8.0.2
  equatable: ^2.0.5
  internet_connection_checker_plus: ^2.5.2
  flutter_svg: ^2.0.14
  keyboard_dismisser: ^3.0.0
  cached_network_image: ^3.4.1
  shared_preferences: ^2.3.3
  shimmer: ^3.0.0
  flutter_screenutil: ^5.9.3
  mask_text_input_formatter: ^2.9.0
  connectivity_plus: ^6.1.3
  internet_connection_checker: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter



  flutter_lints: ^5.0.0

flutter:

  generate: true
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/fonts/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Light.ttf
          weight: 300
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700

flutter_intl:
  enabled: true
  class_name: AppLocalization
  arb-dir: lib/l10n
  template-arb-file: intl_uz.arb
  preferred-supported-locales:
    - uz
    - en
    - ru
  use-deferred-loading: true