name: drugpromotion
description: "Delivery project"

publish_to: 'none'

version: 1.0.1+120

environment:
  sdk: ^3.6.0

dependencies:
  sentry_flutter: ^8.14.2
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  yandex_mapkit: ^4.1.0
  flutter_bloc: ^9.0.0
  intl: ^0.20.2
  dio: ^5.7.0
  get_it: ^8.0.2
  equatable: ^2.0.5
  flutter_svg: ^2.0.14
  keyboard_dismisser: ^3.0.0
  cached_network_image: ^3.4.1
  shared_preferences: ^2.3.3
  shimmer: ^3.0.0
  flutter_screenutil: ^5.9.3
  mask_text_input_formatter: ^2.9.0
  firebase_core: ^3.12.1
  provider: ^6.1.4
  image_picker: ^1.1.2
  geolocator: ^13.0.4
  firebase_messaging: ^15.2.5
  camera: ^0.11.1
  chucker_flutter: ^1.8.5
  sentry_dio: ^8.14.2
  webview_flutter: ^4.11.0
  url_launcher: ^6.3.1

dev_dependencies:
  sentry_dart_plugin: ^2.4.1
  flutter_launcher_icons: "^0.14.3"
  flutter_test:
    sdk: flutter



  flutter_lints: ^5.0.0

flutter:

  generate: true
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/fonts/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Light.ttf
          weight: 300
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700

flutter_intl:
  enabled: true
  class_name: AppLocalization
  arb-dir: lib/l10n
  template-arb-file: intl_uz.arb
  preferred-supported-locales:
    - uz
    - en
    - ru
  use-deferred-loading: true
sentry:
  upload_debug_symbols: true
  upload_source_maps: true
  project: flutter
  org: drug-promotion